version: '3.4'

networks:
  main:
    external: true

services:
  gatekeeper:
    image: traefik:2.0
    container_name: "gatekeeper"
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--global.sendAnonymousUsage=false"
    networks:
      - main
    ports:
      - target: 80            
        published: 80
        mode: host            
      - target: 8080          
        published: 7000       
        mode: host
     
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.gatekeeper.rule=Host(`localhost`)"
      - "traefik.http.routers.gatekeeper.entrypoints=web"
      - "traefik.http.services.gatekeeper.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  webapi:
    container_name: "apibox.api.webapi"
    image: ${DOCKER_REGISTRY-}apiboxapiwebapi
    build:
      context: .
      dockerfile: ApiBox.Api.WebApi/Dockerfile
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapi.rule=Host(`localhost`) && PathPrefix(`/apibox/webapi`)"
     

  odata:
    container_name: "apibox.api.odata"
    image: ${DOCKER_REGISTRY-}apiboxapiodata
    build:
      context: .
      dockerfile: ApiBox.Api.OData/Dockerfile
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odata.rule=Host(`localhost`) && PathPrefix(`/apibox/odata`)"

  grpc:
    container_name: "apibox.api.grpc"
    image: ${DOCKER_REGISTRY-}apiboxapigrpc
    ports:
      - target: 8443            
    build:
      context: .
      dockerfile: ApiBox.Api.gRPC/Dockerfile
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grpc.rule=Host(`localhost`) && PathPrefix(`/apibox/grpc`)"
      - "traefik.http.services.grpc.loadbalancer.server.scheme=h2c"


  gqlnet_gtf:
    container_name: "apibox.api.gqlnet_gtf"
    image: ${DOCKER_REGISTRY-}apiboxapigraphqldotnetgraphtypesfirst
    build:
      context: .
      dockerfile: ApiBox.Api.GraphQLDotNet.GraphTypesFirst/Dockerfile
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gqlnet_gtf.rule=Host(`localhost`) && PathPrefix(`/apibox/gqlnet_gtf`)"

