version: '3.4'

networks:
  main:
    external: true

services:
  webapi:
    container_name: "apibox.api.webapi"
    image: ${DOCKER_REGISTRY-}apiboxapiwebapi
    build:
      context: .
      dockerfile: ApiBox.Api.WebApi/Dockerfile
    networks:
      - main

  odata:
    container_name: "apibox.api.odata"
    image: ${DOCKER_REGISTRY-}apiboxapiodata
    build:
      context: .
      dockerfile: ApiBox.Api.OData/Dockerfile
    networks:
      - main

  gqlnet_gtf:
    container_name: "apibox.api.gqlnet_gtf"
    image: ${DOCKER_REGISTRY-}apiboxapigraphqldotnetgraphtypesfirst
    build:
      context: .
      dockerfile: ApiBox.Api.GraphQLDotNet.GraphTypesFirst/Dockerfile
    networks:
      - main

  grpc:
    container_name: "apibox.api.grpc"
    image: ${DOCKER_REGISTRY-}apiboxapigrpc
    build:
      context: .
      dockerfile: ApiBox.Api.gRPC/Dockerfile
    networks:
      - main